# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
[toolchain]
channel = "nightly-2024-06-16"
components = [
    "cargo",
	"clippy",
    "rust-src",
    "rustc",
	"rustfmt",
	"llvm-tools",
	"rust-analyzer",
]
