# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, settings, ... }:
let
  nvidia-offload = pkgs.writeTextFile {
   name = "nvidia-offload";
   destination = "/bin/nvidia-offload";
   executable = true;

   text = ''
export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
exec "$@"
   '';
  };
in {
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  environment.sessionVariables = {
    # NIXOS_OZONE_WL = "1";
    LIBVA_DRIVER_NAME = "nvidia";
    # LIBVA_DRIVER_NAME = "iHD";  # https://github.com/intel/libva/issues/575; nvidia-vaapi-driver doesn't work with my optimus laptop
    __GLX_VENDOR_LIBRARY_NAME = "nvidia";
    WLR_NO_HARDWARE_CURSORS = "1";  # nvidia problems
    # WLR_NO_HARDWARE_CURSORS = "0";

    NVD_BACKEND = "direct";
    GBM_BACKEND = "nvidia-drm";
    # using nvidia 545 drivers, this no longer crashes Hyprland
    # but it crashes Firefox instead... when it opens a pdf (through the .application file)
    # apparently this is documented in https://wiki.hyprland.org/Nvidia/
  };

  services.xserver.videoDrivers = ["nvidia"];

  environment.systemPackages = [
    nvidia-offload
  ];

  hardware.nvidia = {
    modesetting.enable = true;

    prime = {
      # sync.enable = true;
      offload = {
        enable = true;
        enableOffloadCmd = true;
      };

      intelBusId = "PCI:0:2:0";
      nvidiaBusId = "PCI:1:0:0";
    };

    open = false;
    # open = true;
    nvidiaSettings = true;

    # package = config.boot.kernelPackages.nvidiaPackages.vulkan_beta;
    package = config.boot.kernelPackages.nvidiaPackages.beta;
    # package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  powerManagement.enable = false;  # this makes NVreg_PreserveVideoMemoryAllocations = 1, which causes problems with open source driver, so unset
  # I don't know what unset here means: have it set to false or true?
  # powerManagement.enable = true;

  boot.kernelParams = [
    "nvidia_drm.modeset=1"
    # "nvidia.NVreg_PreserveVideoMemoryAllocations=1"  # https://github.com/NVIDIA/open-gpu-kernel-modules/issues/472
    "nvidia.NVreg_PreserveVideoMemoryAllocations=0"  # this fixes it
    # "module_blacklist=i915" 
  ];
  boot.extraModprobeConfig = ''
    options nvidia-drm modeset=1
    options nvidia-drm fbdev=1

    options thinkpad_acpi fan_control=1
  '';

  # boot.extraModulePackages = [ config.boot.kernelPackages.nvidia_x11 ];
  boot.extraModulePackages = [ ];
  boot.initrd.kernelModules = [ "nvidia" ];
}

